export const muscles = [
  { id: 1, name: "Abdominals" },
  { id: 2, name: "Abductors" },
  { id: 3, name: "Adductors" },
  { id: 4, name: "Biceps" },
  { id: 5, name: "Calves" },
  { id: 6, name: "Cardio" },
  { id: 7, name: "Chest" },
  { id: 8, name: "Forearms" },
  { id: 9, name: "Full Body" },
  { id: 10, name: "Glutes" },
  { id: 11, name: "Hamstrings" },
  { id: 12, name: "Lats" },
  { id: 13, name: "Lower Back" },
  { id: 14, name: "Neck" },
  { id: 15, name: "Quadriceps" },
  { id: 16, name: "Shoulders" },
  { id: 17, name: "Traps" },
  { id: 18, name: "Triceps" },
  { id: 19, name: "Upper Back" },
  { id: 20, name: "Other" },
];
